"""Offline, bounded diagnostics analysis primitives."""

from .archive import (
    DEFAULT_LIMITS,
    ArchiveLimits,
    ArchiveReadError,
    discover_archives,
    load_diagnostic_archive,
)
from .models import (
    ANALYSIS_SCHEMA_VERSION,
    ANALYZER_VERSION,
    RULE_SET_VERSION,
    SUPPORTED_INSTALLATION_ID_SCHEMA_VERSIONS,
    SUPPORTED_REPORT_SCHEMA_VERSIONS,
    ArchiveAnalysis,
    ArchiveMetadata,
    ArchiveStatus,
    Confidence,
    Controller,
    ControllerObservation,
    DiagnosticReport,
    Finding,
    LoadedDiagnosticArchive,
    NormalizedValue,
    Severity,
    ValueStatus,
    to_json_value,
)

__all__ = [
    "ANALYSIS_SCHEMA_VERSION",
    "ANALYZER_VERSION",
    "RULE_SET_VERSION",
    "SUPPORTED_INSTALLATION_ID_SCHEMA_VERSIONS",
    "SUPPORTED_REPORT_SCHEMA_VERSIONS",
    "ArchiveAnalysis",
    "ArchiveLimits",
    "ArchiveMetadata",
    "ArchiveReadError",
    "ArchiveStatus",
    "Confidence",
    "Controller",
    "ControllerObservation",
    "DEFAULT_LIMITS",
    "DiagnosticReport",
    "Finding",
    "LoadedDiagnosticArchive",
    "NormalizedValue",
    "Severity",
    "ValueStatus",
    "discover_archives",
    "load_diagnostic_archive",
    "to_json_value",
]
