# Złącze GEN: napięcia, prądy, moc oraz energia

sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Voltage L1"
    id: gen_voltage_a_103
    register_type: read
    address: 103
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Voltage L2"
    id: gen_voltage_b_104
    register_type: read
    address: 104
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Voltage L3"
    id: gen_voltage_c_105
    register_type: read
    address: 105
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Current L1"
    id: gen_current_a_106
    register_type: read
    address: 106
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_WORD
    filters:
    - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Current L2"
    id: gen_current_b_107
    register_type: read
    address: 107
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_WORD
    filters:
    - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Current L3"
    id: gen_current_c_108
    register_type: read
    address: 108
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    value_type: S_WORD
    filters:
    - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Active Power L1"
    id: gen_active_power_a_109
    register_type: read
    address: 109
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:flash
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Active Power L2"
    id: gen_active_power_b_110
    register_type: read
    address: 110
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:flash
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Active Power L3"
    id: gen_active_power_c_111
    register_type: read
    address: 111
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:flash
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy Total"
    id: generator_energy_total_8304
    register_type: read
    address: 2070
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_DWORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy L1n Total"
    id: generator_energy_an_total_8306
    register_type: read
    address: 2072
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_DWORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy L2n Total"
    id: generator_energy_bn_total_8308
    register_type: read
    address: 2074
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_DWORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy L3n Total"
    id: generator_energy_cn_total_8310
    register_type: read
    address: 2076
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_DWORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy Total Today"
    id: generator_energy_total_today_8495
    register_type: read
    address: 2135
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy L1n Today"
    id: generator_energy_an_today_8496
    register_type: read
    address: 2136
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy L2n Today"
    id: generator_energy_bn_today_8497
    register_type: read
    address: 2137
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Energy L3n Today"
    id: generator_energy_cn_today_8498
    register_type: read
    address: 2138
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    icon: mdi:counter
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
    - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Total Power"
    id: generator_total_power_8557
    register_type: read
    address: 2173
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:flash
    accuracy_decimals: 0
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Power L1n"
    id: generator_power_an_8558
    register_type: read
    address: 2174
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:flash
    accuracy_decimals: 0
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Power L2n"
    id: generator_power_bn_8559
    register_type: read
    address: 2175
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:flash
    accuracy_decimals: 0
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Power L3n"
    id: generator_power_cn_8560
    register_type: read
    address: 2176
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    icon: mdi:flash
    accuracy_decimals: 0
    value_type: U_WORD
